spring:
  application:
    api-prefix: ${API_PREFIX:/api/v1}
    name: spring-boot-rest-api
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
server:
  port: ${API_PORT:3000}

payment:
  vnPay:
    url: ${PAY_URL:https://sandbox.vnpayment.vn/paymentv2/vpcpay.html}
    tmnCode: ${TMN_CODE:58X4B4HP}
    secretKey: ${SECRET_KEY:VRLDWNVWDNPCOEPBZUTWSEDQAGXJCNGZ}
    returnUrl: ${RETURN_URL:http://localhost:3000/api/v1/payment/vn-pay-callback}
    version: ${VERSION:2.1.0}
    command: ${COMMAND:pay}
    orderType: ${ORDER_TYPE:other}





